code_blocks:
  theme: ocean
  copy_button: true
  highlight: true
  line_number: true
  word_wrap: true
  expand: false

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true